### ISSUE TITLE
Consistent file names

### ISSUE THREAD

**Issue by hadley** [COSTDataExpo2013/QuachSymanzikForsgren#2]
Since you have `01_data_cleaning.R`, maybe number all the files so it's obvious what order to run them in?

**Comment by rfgeek** [comment]
I actually mentioned in the Read_Me.R file that it doesn't matter which order the rest of the .R files are ran. 01_data_cleaning.R just need to be ran first. I just now modified the .R files names so now there is some ordering in which the .R files need to be ran .
