### ISSUE TITLE
Downloading files

### ISSUE THREAD

**Issue by hadley** [COSTDataExpo2013/QuachSymanzikForsgren#3]
It would be nice to check to see if the files have already been downloaded, or at least comment that `01_data_cleaning.R` only needs to be run once

**Comment by hadley** [comment]
Also, the downloads fail:

``` R
> source('~/Desktop/expo2013/QuachSymanzikForsgren/01_data_cleaning.R')
# trying URL 'http://www.soulofthecommunity.org/sites/default/files/SOCTData2008Por.zip'
# Content type 'text/html; charset=iso-8859-1' length 348 bytes
```

so it might be nicer include the data directly in the package.

**Comment by hadley** [comment]
I can't get any further without this data, so I'll wait until this is fixed before proceeding with the rest of the code/reproducibility review

**Comment by rfgeek** [comment]
Hi  Hadley,

I just got back into the country yesterday and I am presenting at JSM soon. I will address these issues after I get back from JSM.

**Comment by rfgeek** [comment]
I have commented that 01_data_cleaning.R only needs to be ran once in 01_data_cleaning.R.
I have provided the data sets instead. 01_data_cleaning.R is now modified so that it is not downloading  the data sets.
